### PR TITLE
Reverse zones are updated as case insensitive

### LINKED ISSUE #957: Reverse zone not recognized as reverse if name is uppercase
**Describe the bug**
if connected zone is named ie. "0.1.10.IN-ADDR.ARPA" it is not recognized as reverse zone. PTR records are not valid  

**VinylDNS Version**
0.9.5-SNAPSHOT

**To Reproduce**
1. connect a reverse zone and name it uppercase
2. try add a new PTR rr
4. See error: "...PTR is not valid in forward lookup zone"

**Expected behavior**
both upper and lower case names should work

### PR DESCRIPTION
**Pull request by Jay07GIT**
Fixes #957.

Changes in this pull request:
- Reverse zone are updated with case insensitive.
- `PTR` records can be added in the `reverse_zone` irrespective of its upper and lower cases.

### CODE REVIEW

File: modules/api/src/main/scala/vinyldns/api/domain/ReverseZoneHelpers.scala [hunk 1]
```diff
@@ -62,7 +63,7 @@ object ReverseZoneHelpers {
     }
 
   def convertPTRtoIPv4(zone: Zone, recordName: String): String = {
```
Comment (nspadaccino) [inline modules/api/src/main/scala/vinyldns/api/domain/ReverseZoneHelpers.scala:65]: I think it would be good to have some additional unit tests in `vinyldns/api/domain/ReverseZoneHelpersSpec.scala` to test the case insensitivity of this method and `convertPTRtoIPv6`

**Review by Aravindh-Raju — DISMISSED** [review]

File: modules/api/src/main/scala/vinyldns/api/domain/ReverseZoneHelpers.scala (hunk 1 above)
Comment (Jay07GIT) [reply modules/api/src/main/scala/vinyldns/api/domain/ReverseZoneHelpers.scala:65]: Added reverse zone unit test cases with uppercase as suggested.

File: modules/api/src/main/scala/vinyldns/api/domain/ReverseZoneHelpers.scala [hunk 2]
```diff
@@ -62,7 +63,7 @@ object ReverseZoneHelpers {
...
-    val zoneName = zone.name.split("in-addr.arpa.")(0)
+    val zoneName = Pattern.compile("in-addr.arpa.", Pattern.CASE_INSENSITIVE).split(zone.name)(0)
```
Comment (remerle) [inline modules/api/src/main/scala/vinyldns/api/domain/ReverseZoneHelpers.scala:66]: This is not idiomatic Scala. We want to try to avoid pulling in Java libraries. To do this in Scala, you would use the `.r` function:

```scala
    val zoneName = "(?i)in-addr.arpa.".r.split(zone.name)(0)
```

However, this seems like overkill when we're just trying to remove the suffix. Instead, we can do this:
```suggestion
    val zoneName = zone.name.dropRight("in-addr.arpa.".length)
```

**Review by remerle — CHANGES_REQUESTED** [review]

File: modules/api/src/main/scala/vinyldns/api/domain/ReverseZoneHelpers.scala (hunk 2 above)
Comment (Jay07GIT) [reply modules/api/src/main/scala/vinyldns/api/domain/ReverseZoneHelpers.scala]: Updated the code as suggested.

File: modules/core/src/main/scala/vinyldns/core/domain/zone/Zone.scala [hunk 3]
```diff
@@ -51,8 +51,8 @@ final case class Zone(
     isTest: Boolean = false,
     backendId: Option[String] = None
 ) {
-  val isIPv4: Boolean = name.endsWith("in-addr.arpa.")
-  val isIPv6: Boolean = name.endsWith("ip6.arpa.")
+  val isIPv4: Boolean = name.endsWith("in-addr.arpa.") || name.endsWith("IN-ADDR.ARPA.")
+  val isIPv6: Boolean = name.endsWith("ip6.arpa.") || name.endsWith("IP6.ARPA.")
```
[the remark this answers is not in the document]
Comment (Jay07GIT) [reply modules/core/src/main/scala/vinyldns/core/domain/zone/Zone.scala]: Updated the code as suggested.

**Review by remerle — APPROVED** [review]
