### PR TITLE
Account for maximum batch entries in SQS SendMessageBatchRequest

### LINKED ISSUE #347: SQS sendBatch needs to account for maximum entries for partition
**Describe the bug**
AWS currently has a restriction on the maximum number of entries within a batch for a `SendMessageBatchRequest` (10). We are currently partitioning if the batch size is greater than the maximum payload size for a message, but need to account for the maximum number as well.

**To Reproduce**
1. Spin up instance of VinylDNS with an SQS instance (setup in AWS, not locally)
2. Send a batch change request with more than 10 requests.

**Stack trace or error log output**
```
com.amazonaws.services.sqs.model.TooManyEntriesInBatchRequestException: Maximum number of entries per request are 10. You have sent 15. (Service: AmazonSQS; Status Code: 400; Error Code: AWS.SimpleQueueService.TooManyEntriesInBatchRequest)
```

### PR DESCRIPTION
**Pull request by mitruly**
Fixes #347.

Changes in this pull request:
- Add `MAXIMUM_BATCH_ENTRY_COUNT`
- Take lower of `MAXIMUM_BATCH_ENTRY_COUNT` and `maxMessageGroupCount` when partitioning batch change request into `SendMessageBatchRequest`

### CODE REVIEW

File: modules/sqs/src/main/scala/vinyldns/sqs/queue/SqsMessageQueue.scala [hunk 1]
```diff
@@ -174,6 +174,7 @@ object SqsMessageQueue extends ProtobufConversions {
   final val MINIMUM_VISIBILITY_TIMEOUT = 0
   final val MAXIMUM_VISIBILITY_TIMEOUT = 43200
   final val MAXIMUM_BATCH_SIZE = 262144
+  final val MAXIMUM_BATCH_ENTRY_COUNT = 10 // Hard limit on the max entries per message batch
```
Comment (mitruly) [inline modules/sqs/src/main/scala/vinyldns/sqs/queue/SqsMessageQueue.scala]: Hardcoded this since this is an AWS SQS limit; could update `sendBatch` to take in a `MessageCount` parameter, but would require updating the signature of `sendBatch`.

File: modules/sqs/src/test/scala/vinyldns/sqs/queue/SqsMessageQueueSpec.scala [hunk 2]
```diff
@@ -52,23 +56,43 @@ class SqsMessageQueueSpec
...
+        yield
+          makeTestAddChange(rsOk, okZone).copy(
+            singleBatchChangeIds = largeRsChange.singleBatchChangeIds)
       val commands = NonEmptyList.fromListUnsafe(recordSetChanges.toList)
+
       toSendMessageBatchRequest(commands).length shouldBe 1
     }
 
     "create multiple batch requests if total message payload is over 256KB" in {
-      val messageSize = messageData(makeTestAddChange(rsOk, okZone)).getBytes().length
```
Comment (mitruly) [inline modules/sqs/src/test/scala/vinyldns/sqs/queue/SqsMessageQueueSpec.scala]: These are four batches of one message each.

File: modules/sqs/src/test/scala/vinyldns/sqs/queue/SqsMessageQueueSpec.scala [hunk 3]
```diff
@@ -52,23 +56,43 @@ class SqsMessageQueueSpec
...
-        yield makeTestAddChange(rsOk, okZone)
+        yield
+          makeTestAddChange(rsOk, okZone).copy(
+            singleBatchChangeIds = largeRsChange.singleBatchChangeIds)
       val commands = NonEmptyList.fromListUnsafe(recordSetChanges.toList)
       toSendMessageBatchRequest(commands).length shouldBe 4
     }
+
+    "allow at most MAXIMUM_BATCH_ENTRY_COUNT items in a batch" in {
+      val rsChange = makeTestAddChange(rsOk, okZone).copy(singleBatchChangeIds = List("a" * 1800))
```
Comment (mitruly) [inline modules/sqs/src/test/scala/vinyldns/sqs/queue/SqsMessageQueueSpec.scala]: This is two batches of multiple messages each.

File: modules/sqs/src/main/scala/vinyldns/sqs/queue/SqsMessageQueue.scala (hunk 1 above)
Comment (nimaeskandary) [reply modules/sqs/src/main/scala/vinyldns/sqs/queue/SqsMessageQueue.scala]: Can you leave a note saying this the aws sqs limit with a link to https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-client-side-buffering-request-batching.html#configuring-buffered-async-client ?
