### PR TITLE
move zone change processing into zone sync handler

### LINKED ISSUE #391: zoneChange status changes to 'Synced' before zone sync completes
**Describe the bug**
In the CommandHandler whenever a zone is created or synced we update the zoneChange status and the zone status, however we are updating the zoneChange status before the zone actually syncs or updates. https://github.com/vinyldns/vinyldns/blob/947de02f4a2202bb106bee019a6e46f543e671ca/modules/api/src/main/scala/vinyldns/api/backend/CommandHandler.scala#L135 This is causing intermittent failures in our func tests.

We also should check if a zone status is Syncing we shouldn't allow another sync to go through

### PR DESCRIPTION
**Pull request by britneywright**
Fixes #391.

Changes in this pull request:
- move the zone change handling for zone creates and syncs into the ZoneSyncHandler

### CODE REVIEW

File: modules/api/src/main/scala/vinyldns/api/engine/ZoneSyncHandler.scala [hunk 1]
```diff
@@ -35,71 +41,108 @@ object ZoneSyncHandler extends DnsConversions with Monitored {
...
+      zoneChangeRepository: ZoneChangeRepository,
+      zoneChange: ZoneChange): IO[ZoneChange] =
+    zoneRepository.save(zoneChange.zone).flatMap {
+      case Left(duplicateZoneError) =>
+        zoneChangeRepository.save(
+          zoneChange.copy(
+            status = ZoneChangeStatus.Failed,
+            systemMessage = Some(duplicateZoneError.message))
+        )
+      case Right(_) if zoneChange.zone.status == ZoneStatus.Active =>
```
Comment (rebstar6) [inline modules/api/src/main/scala/vinyldns/api/engine/ZoneSyncHandler.scala]: just do `case Right(_) => save...` here with no status changes. 

let the proper status be passed in (so have runSync change the status to `ZoneChangeStatus.Synced` in that logic)

File: modules/api/src/main/scala/vinyldns/api/engine/ZoneSyncHandler.scala [hunk 2]
```diff
@@ -35,71 +41,108 @@ object ZoneSyncHandler extends DnsConversions with Monitored {
...
-              } yield
-                zoneChange.copy(
-                  zone.copy(status = ZoneStatus.Active, latestSync = Some(DateTime.now)))
-            }
+            // join together the results of saving both the record changes as well as the record sets
+            for {
+              _ <- saveRecordChanges
+              _ <- saveRecordSets
+            } yield
+              zoneChange.copy(
```
Comment (rebstar6) [inline modules/api/src/main/scala/vinyldns/api/engine/ZoneSyncHandler.scala]: ah yeah right here! make it active here

File: modules/api/src/main/scala/vinyldns/api/engine/ZoneSyncHandler.scala [hunk 3]
```diff
@@ -35,71 +41,108 @@ object ZoneSyncHandler extends DnsConversions with Monitored {
...
-                zoneChange.copy(
-                  zone.copy(status = ZoneStatus.Active, latestSync = Some(DateTime.now))))
-            } else {
-              logger.info(
-                s"Zone sync for change $zoneChange found ${changes.size} changes to be saved")
-              val changeSet = ChangeSet(changes).copy(status = ChangeSetStatus.Applied)
+          if (changes.isEmpty) {
+            logger.info(s"Zone sync for change $zoneChange had no records to sync")
+            IO.pure(
+              zoneChange.copy(
```
Comment (rebstar6) [inline modules/api/src/main/scala/vinyldns/api/engine/ZoneSyncHandler.scala]: and here, synced

**Comment by mitruly** [comment]
I think we should try to keep coverage consistent or at least pass the 0.1% threshold.

**Comment by britneywright** [comment]
new tests are still a work in progress, but I think the zoneSyncHandler logic is all there.

File: modules/api/src/main/scala/vinyldns/api/engine/ZoneSyncHandler.scala [hunk 4]
```diff
@@ -35,71 +41,107 @@ object ZoneSyncHandler extends DnsConversions with Monitored {
...
+        _ <- saveZoneAndChange(zoneRepository, zoneChangeRepository, syncChange) // zone status: Active
+      } yield syncChange
 
-          val dnsView = time(s"zone.sync.loadDnsView(${zoneChange.id})")(dnsLoader(zone).load())
-          val vinyldnsView = time(s"zone.sync.loadVinylDNSView(${zoneChange.id})")(
-            vinyldnsLoader(zone, recordSetRepository).load())
-          val recordSetChanges = (dnsView, vinyldnsView).parTupled.map {
-            case (dnsZoneView, vinylDnsZoneView) => vinylDnsZoneView.diff(dnsZoneView)
-          }
+  def saveZoneAndChange(
```
Comment (mitruly) [inline modules/api/src/main/scala/vinyldns/api/engine/ZoneSyncHandler.scala]: Discussed this with @britneywright a little bit and would like to open up the discussion to others: Think that bringing in `saveZoneAndChange` here is not needed since we could just update `ZoneChangeHandler.apply` to have a success case of `case Right(_) => zoneChangeRepository.save(zoneChange)`.

This would require that `ZoneChangeGenerator` to set the expected `ZoneChangeStatus` (potentially having different statuses for the front and back engines).

File: modules/api/src/main/scala/vinyldns/api/backend/CommandHandler.scala [hunk 5]
```diff
@@ -134,14 +134,7 @@ object CommandHandler {
       message.command match {
         case sync: ZoneChange
             if sync.changeType == ZoneChangeType.Sync || sync.changeType == ZoneChangeType.Create =>
-          val doSync =
-            for {
-              _ <- zoneChangeProcessor(sync) // make sure zone is updated to a syncing status
```
[the remark this answers is not in the document]
Comment (rebstar6) [reply modules/api/src/main/scala/vinyldns/api/backend/CommandHandler.scala]: while it's a bit copy/paste-y, i think the benefits of having the concerns separated outweigh the added lines. right now, the sharing is what made it easy for this bug to be introduced.

the alternative would be to have a `ZoneChangeSaver` that does a clean save and pass that into both the ZoneSyncHandler and ZoneChangeHandler, but may not be worth the overhead

File: modules/api/src/main/scala/vinyldns/api/engine/ZoneSyncHandler.scala [hunk 6]
```diff
@@ -35,71 +41,107 @@ object ZoneSyncHandler extends DnsConversions with Monitored {
...
+      zoneRepository: ZoneRepository,
       dnsLoader: Zone => DnsZoneViewLoader = DnsZoneViewLoader.apply,
       vinyldnsLoader: (Zone, RecordSetRepository) => VinylDNSZoneViewLoader =
         VinylDNSZoneViewLoader.apply): ZoneChange => IO[ZoneChange] =
     zoneChange =>
-      monitor("zone.sync") {
-        time(s"zone.sync(${zoneChange.zoneId})") {
-          val zone = zoneChange.zone
+      for {
+        _ <- saveZoneAndChange(zoneRepository, zoneChangeRepository, zoneChange) // zone status: Syncing
```
[the remark this answers is not in the document]
Comment (rebstar6) [reply modules/api/src/main/scala/vinyldns/api/engine/ZoneSyncHandler.scala]: agreed - just update the comment. can say something like `initial save to store zone status as syncing` or something.

File: modules/api/src/test/scala/vinyldns/api/engine/ZoneSyncHandlerSpec.scala [hunk 7]
```diff
@@ -164,31 +166,154 @@ class ZoneSyncHandlerSpec
...
+  "ZoneSyncHandler" should {
+    "process successful zone sync" in {
+      doReturn(IO.pure(Right(testZoneChange)))
+        .when(zoneRepo)
+        .save(any[Zone])
+
+      val dnsLoader = mock[Zone => DnsZoneViewLoader]
+      doReturn(mockDNSLoader).when(dnsLoader).apply(any[Zone])
+
+      val syncer = ZoneSyncHandler(
```
Comment (mitruly) [inline modules/api/src/test/scala/vinyldns/api/engine/ZoneSyncHandlerSpec.scala]: Feel that most of these tests can consolidate these sync handlers as well, since there are like three variations that can be defined for all tests to use:
```
  private val mockDnsZoneViewLoader = mock[Zone => DnsZoneViewLoader]

  private val zoneSync = ZoneSyncHandler(
    recordSetRepo,
    recordChangeRepo,
    zoneChangeRepo,
    zoneRepo,
    mockDnsZoneViewLoader,
    (_, _) => mockVinylDNSLoader)
  private val zoneSyncDnsLoader = ZoneSyncHandler(
    recordSetRepo,
    recordChangeRepo,
    zoneChangeRepo,
    zoneRepo,
    _ => mockDNSLoader,
    (_, _) => mockVinylDNSLoader)
  private val runZoneSync = ZoneSyncHandler.runSync(
    recordSetRepo,
    recordChangeRepo,
    testZoneChange,
    _ => mockDNSLoader,
    (_, _) => mockVinylDNSLoader)
```

File: modules/api/src/test/scala/vinyldns/api/engine/ZoneSyncHandlerSpec.scala [hunk 8]
```diff
@@ -164,31 +181,134 @@ class ZoneSyncHandlerSpec
...
+  "runSync" should {
+    "send the correct zone to the DNSZoneViewLoader" in {
       val captor = ArgumentCaptor.forClass(classOf[Zone])
 
       val dnsLoader = mock[Zone => DnsZoneViewLoader]
       doReturn(mockDNSLoader).when(dnsLoader).apply(any[Zone])
 
       val syncer =
-        ZoneSyncHandler(recordSetRepo, recordChangeRepo, dnsLoader, (_, _) => mockVinylDNSLoader)
+        ZoneSyncHandler.runSync(
```
Comment (mitruly) [inline modules/api/src/test/scala/vinyldns/api/engine/ZoneSyncHandlerSpec.scala]: We generally don't need to create intermediate variables (eg. `syncer` in most places) if they aren't being used. This can just be:
```
     ZoneSyncHandler.runSync(
          recordSetRepo,
          recordChangeRepo,
          testZoneChange,
          dnsLoader,
          (_, _) => mockVinylDNSLoader).unsafeRunSync()
```

File: modules/api/src/test/scala/vinyldns/api/engine/ZoneSyncHandlerSpec.scala [hunk 9]
```diff
@@ -164,31 +181,132 @@ class ZoneSyncHandlerSpec
...
+      result.zone.status shouldBe ZoneStatus.Active
+      result.zone.latestSync should not be defined
+    }
+  }
+
+  "saveZoneAndChange" should {
+    "save zone and zoneChange with given statuses" in {
+      doReturn(IO.pure(Right(testZoneChange))).when(zoneRepo).save(testZoneChange.zone)
+
+      val saver = ZoneSyncHandler.saveZoneAndChange(zoneRepo, zoneChangeRepo, testZoneChange)
```
Comment (mitruly) [inline modules/api/src/test/scala/vinyldns/api/engine/ZoneSyncHandlerSpec.scala]: Can we also remove `saver` here?

File: modules/api/src/test/scala/vinyldns/api/engine/ZoneSyncHandlerSpec.scala [hunk 10]
```diff
@@ -164,31 +181,132 @@ class ZoneSyncHandlerSpec
...
+
+      savedChange.status shouldBe ZoneChangeStatus.Pending
+      savedChange.zone.status shouldBe ZoneStatus.Syncing
+      savedChange.zone.latestSync shouldBe testZoneChange.zone.latestSync
+    }
+
+    "handle duplicateZoneError" in {
+      doReturn(IO.pure(Left(DuplicateZoneError("error")))).when(zoneRepo).save(testZoneChange.zone)
+
+      val saver = ZoneSyncHandler.saveZoneAndChange(zoneRepo, zoneChangeRepo, testZoneChange)
```
Comment (mitruly) [inline modules/api/src/test/scala/vinyldns/api/engine/ZoneSyncHandlerSpec.scala]: `saver` here, too.
